const LOG_ACTIONS = Object.freeze({
  REGISTER_USER: "REGISTER_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  ADD_USER_SKILLS: "ADD_USER_SKILLS",
  REMOVE_USER_SKILL: "REMOVE_USER_SKILL",
  REMOVE_USER_SKILLS: "REMOVE_USER_SKILLS",
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  CREATE_REVIEW: "CREATE_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  APPLY_CERTIFICATION: "APPLY_CERTIFICATION",
  APPROVE_CERTIFICATION: "APPROVE_CERTIFICATION",
  REJECT_CERTIFICATION: "REJECT_CERTIFICATION",
});

const LOG_ENTITIES = Object.freeze({
  USER: "User",
  PROJECT: "Project",
  REVIEW: "Review",
  SKILL: "Skill",
  CERTIFICATION_REQUEST: "CertificationRequest",
});

const ACTION_VALUES = Object.freeze(Object.values(LOG_ACTIONS));
const ENTITY_VALUES = Object.freeze(Object.values(LOG_ENTITIES));

const EVENT_NAMES = Object.freeze({
  ACTIVITY_LOG_CREATED: "activity-log:created",
});

module.exports = {
  LOG_ACTIONS,
  LOG_ENTITIES,
  ACTION_VALUES,
  ENTITY_VALUES,
  EVENT_NAMES,
};