module.exports = Object.freeze({
  VALIDATION: "ERR_VALIDATION",
  NOT_FOUND: "ERR_NOT_FOUND",
  DUPLICATE: "ERR_DUPLICATE",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  FORBIDDEN: "ERR_FORBIDDEN",
  INTERNAL: "ERR_INTERNAL",
  GENERIC: "ERR_GENERIC",
});